version: "3"

services:
  node-app:
    build:
      context: .
      # Change the location of the docker file to DockerFiles/Dockerfile-Node
      dockerfile: DockerFiles/Dockerfile-Node
    ports:
      - "8080:8080"

  python-broker:
    build:
      context: .
      # Change the location of the docker file to DockerFiles/Dockerfile-Python
      dockerfile: DockerFiles/Dockerfile-Python
