# version: "3"

services:
  # subscriber-app:
  #   build:
  #     context: .
  #     dockerfile: DockerFiles/Volumes/Dockerfile-Subscriber

  #   image: pythonsubscriber
  #   volumes:
  #     - ./python_servers/src/:/app
  #   depends_on:
  #     - connector-app
  #   ports:
  #     - "3000:5000"
  #   networks:
  #     - app-network

  # publisher-app:
  #   build:
  #     context: .
  #     dockerfile: DockerFiles/Volumes/Dockerfile-Publisher

  #   image: pythonpublisher

  #   volumes:
  #     - ./python_servers/src/:/app
  #   depends_on:
  #     - subscriber-app
  #   ports:
  #     - "4000:5000"
  #   networks:
  #     - app-network

  # connector-app:
  #   build:
  #     context: .
  #     dockerfile: DockerFiles/Volumes/Dockerfile-Connector
  #   image: pythonconnector
  #   volumes:
  #     - ./python_servers/src/:/app
  #   # depends_on:
  #   #   - database-app
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - app-network

  node-app:
    build:
      context: .
      # Change the location of the docker file to DockerFiles/Dockerfile-Node
      dockerfile: DockerFiles/Volumes/Dockerfile-Website
    image: adguardwebside
    volumes:
      # - ./node_servers/website:/app
      - ./node_servers/website/controllers:/app/controllers
      - ./node_servers/website/model:/app/model
      - ./node_servers/website/public:/app/public
      - ./node_servers/website/routes:/app/routes
      - ./node_servers/website/views:/app/views
      - ./node_servers/website/index.js:/app/index.js
      - ./node_servers/website/.env:/app/.env

    depends_on:
      - database-app
    ports:
      - "8080:8080"
    working_dir: /app
    networks:
      - app-network

  database-app:
    build:
      context: .
      dockerfile: DockerFiles/Volumes/Dockerfile-Database
    image: nodejsdatabase
    volumes:
      - ./node_servers/database_server/controllers:/app/controllers
      - ./node_servers/database_server/model:/app/model
      - ./node_servers/database_server/public:/app/public
      - ./node_servers/database_server/routes:/app/routes
      - ./node_servers/database_server/index.js:/app/index.js
      - ./node_servers/database_server/.env:/app/.env
    ports:
      # - "27017:8080"
      - "6000:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
