version: "3"

x-common-settings: &common-settings
  build:
    context: .
    dockerfile: DockerFiles/Volumes/Dockerfile-Python
  volumes:
    - ./python_servers/src/:/app
  networks:
    - app-network
  restart: unless-stopped

services:
  subscriber-app:
    <<: *common-settings

    image: pythonsubscriber

    depends_on:
      - connector-app
    ports:
      - "3000:5000"
    environment:
      - URL=connector-app
    command: ["python", "subscriber_broker.py"]

  publisher-app:
    <<: *common-settings
    image: pythonpublisher

    depends_on:
      - subscriber-app
    ports:
      - "4000:5000"
    command: ["python", "publisher_broker.py"]

  connector-app:
    <<: *common-settings

    image: pythonconnector
    # depends_on:
    #   - database-app
    ports:
      - "5000:5000"
    command: ["python", "connector_server.py"]

  # node-app:
  #   build:
  #     context: .
  #     dockerfile: DockerFiles/Volumes/Dockerfile-Website
  #   image: adguardwebside
  #   volumes:
  #     # - ./node_servers/website:/app
  #     - ./node_servers/website/controllers:/app/controllers
  #     - ./node_servers/website/model:/app/model
  #     - ./node_servers/website/public:/app/public
  #     - ./node_servers/website/routes:/app/routes
  #     - ./node_servers/website/views:/app/views
  #     - ./node_servers/website/index.js:/app/index.js
  #     - ./node_servers/website/.env:/app/.env
  #     # - ./node_servers/website/package.json:/app/package.json
  #     # - ./node_servers/website/package-lock.json:/app/package-lock.json

  #   depends_on:
  #     - database-app
  #   ports:
  #     - "8080:8080"
  #   working_dir: /app
  #   command: ["npm", "start"]
  #   networks:
  #     - app-network

  # database-app:
  #   build:
  #     context: .
  #     dockerfile: DockerFiles/Volumes/Dockerfile-Database
  #   image: nodejsdatabase
  #   volumes:
  #     - ./node_servers/database_server/controllers:/app/controllers
  #     - ./node_servers/database_server/model:/app/model
  #     - ./node_servers/database_server/public:/app/public
  #     - ./node_servers/database_server/routes:/app/routes
  #     - ./node_servers/database_server/index.js:/app/index.js
  #     - ./node_servers/database_server/.env:/app/.env
  #     # - ./node_servers/database_server/package.json:/app/package.json
  #     # - ./node_servers/database_server/package-lock.json:/app/package-lock.json
  #   ports:
  #     # - "27017:8080"
  #     - "6000:7080"
  #   command: ["npm", "start"]
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
