version: "3"

x-network-restart: &network-restart
  networks:
    - app-network
  restart: unless-stopped

x-common-python: &common-python
  build:
    context: .
    dockerfile: DockerFiles/Volumes/Dockerfile-Python
  volumes:
    - ./python_servers/src/:/app
  <<: *network-restart

x-common-node: &common-node
  command: ["npm", "start"]
  <<: *network-restart

services:
  # subscriber-app:
  #   <<: *common-python

  #   image: pythonsubscriber

  #   depends_on:
  #     - connector-app
  #   ports:
  #     - "3000:5000"
  #   environment:
  #     - URL=connector-app
  #   command: ["python", "subscriber_broker.py"]

  # publisher-app:
  #   <<: *common-python
  #   image: pythonpublisher

  #   depends_on:
  #     - subscriber-app
  #   ports:
  #     - "4000:5000"
  #   command: ["python", "publisher_broker.py"]

  # connector-app:
  #   <<: *common-python

  #   image: pythonconnector
  #   depends_on:
  #     - database-app
  #   ports:
  #     - "5000:5000"
  #   command: ["python", "connector_server.py"]

  node-app:
    build:
      context: .
      dockerfile: DockerFiles/Volumes/Dockerfile-Website
    image: adguardwebside
    volumes:
      - ./node_servers/website/controllers:/app/controllers
      - ./node_servers/website/model:/app/model
      - ./node_servers/website/public:/app/public
      - ./node_servers/website/routes:/app/routes
      - ./node_servers/website/views:/app/views
      - ./node_servers/website/index.js:/app/index.js
      - ./node_servers/website/.env:/app/.env

    depends_on:
      - database-app
    ports:
      - "8080:8080"
    <<: *common-node
    environment:
      - DBURL=database-app

  database-app:
    build:
      context: .
      dockerfile: DockerFiles/Volumes/Dockerfile-Database
    image: nodejsdatabase
    volumes:
      - ./node_servers/database_server/controllers:/app/controllers
      - ./node_servers/database_server/model:/app/model
      - ./node_servers/database_server/public:/app/public
      - ./node_servers/database_server/routes:/app/routes
      - ./node_servers/database_server/index.js:/app/index.js
      - ./node_servers/database_server/.env:/app/.env
    # ports:
    #   - "7080:7080"
    <<: *common-node

networks:
  app-network:
    driver: bridge
