# version: "3"

services:
  python-app:
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile-Python
    image: pythonbroker
    depends_on:
      - node-app
  node-app:
    build:
      context: .
      # Change the location of the docker file to DockerFiles/Dockerfile-Node
      dockerfile: DockerFiles/Dockerfile-Node-Volumes
    # ports:
    #   - "8080:8080"
    image: adguardwebside
    volumes:
      # - ./website:/app
      - ./website/controllers:/app/controllers
      - ./website/model:/app/model
      - ./website/public:/app/public
      - ./website/routes:/app/routes
      - ./website/views:/app/views
      - ./website/index.js:/app/index.js
    ports:
      - "8080:8080"
    working_dir: /app

  # python-broker:
  #   build:
  #     context: .
  #     # Change the location of the docker file to DockerFiles/Dockerfile-Python
  #     dockerfile: DockerFiles/Dockerfile-Python
