# Use an official Python runtime as a parent image

FROM python:3.9-slim

# Set the working directory to /app

WORKDIR /app

COPY python_servers/requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt


EXPOSE 5000

