# Base Image

# Use an official Node.js runtime as a base image

FROM node:18.16-alpine

# Set the working directory to /app

WORKDIR /app


# Install app dependencies
COPY node_servers/website/package*.json ./

# Install dependencies
RUN npm ci


# # Install app dependencies

# COPY node_servers/website/package.json ./

# # Install dependencies

# RUN npm i


# Expose port 8080 (adjust as needed)

EXPOSE 8080

# Run app

CMD ["npm", "start"]
