# version: "3"

services:
  python-app:
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile-Python-Volumes
    image: pythonbroker
    volumes:
      - ./broker:/app

    ports:
      - "5000:5000"
    networks:
      - app-network

  node-app:
    build:
      context: .
      # Change the location of the docker file to DockerFiles/Dockerfile-Node
      dockerfile: DockerFiles/Dockerfile-Node-Volumes
    image: adguardwebside
    volumes:
      # - ./website:/app
      - ./website/controllers:/app/controllers
      - ./website/model:/app/model
      - ./website/public:/app/public
      - ./website/routes:/app/routes
      - ./website/views:/app/views
      - ./website/index.js:/app/index.js
    depends_on:
      - python-app
    ports:
      - "8080:8080"
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# -------
