# Base Image

# Use an official Node.js runtime as a base image

# FROM node:14

FROM node:18.16-alpine

# Set the working directory to /app

WORKDIR /app

# Expose port 8080 (adjust as needed)

EXPOSE 8080

# Run app

CMD ["npm", "start"]
