# Base image
FROM node:18.16-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY website/package*.json ./




# Install dependencies
RUN npm ci


COPY website/controllers controllers  
COPY website/model model         
COPY website/public public     
COPY website/routes routes   
COPY website/views views
COPY website/index.js .



# Expose port
EXPOSE 8080

# Run app
CMD ["npm", "start"]

# docker build -t bilbo .

# docker run -d -p 8080:8080 bilbo

# docker exec -it container_id /bin/sh
