# Use an official Python runtime as a parent image

FROM python:3.9-slim

# Set the working directory to /app

WORKDIR /app

COPY broker/requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Make port 80 available to the world outside this container

# EXPOSE 80

EXPOSE 5000

# Define environment variable

ENV NAME World

# Run app.py when the container launches

# CMD ["python", "broker.py"]
CMD ["python", "web_server.py"]
